name: Test

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        run: |
          cargo test
      - name: cargo install
        run: |
          cargo install --path=.
      - name: build --release
        run: |
          cargo build --release
      - name: wiztree-metafile.json
        run: |
          wiztree-metafile . > wiztree-metafile-${{ matrix.os }}.json
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wiztree-metafile-${{ matrix.os }}
          path: |
            wiztree-metafile-${{ matrix.os }}.json
